name: Get Marketplace Identity
on: workflow_dispatch

jobs:
  identity:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}      # or secrets
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      # Get the Azure AD identity of the GitHub Action, resource is a known MS constant
      - run: |
          az rest \
            -u https://app.vssps.visualstudio.com/_apis/profile/profiles/me \
            --resource 499b84ac-1321-427f-aa17-267ca6975798